version: "3.9"

services:
    redis:
        image: redis
        container_name: ${COMPOSE_PROJECT_NAME}_redis
        sysctls:
            net.core.somaxconn: 511
        networks:
            - backend
    php:
        build: ./php/
        image: ${COMPOSE_PROJECT_NAME}_php
        container_name: ${COMPOSE_PROJECT_NAME}_php
        depends_on:
            - redis
        volumes:
            - ../:/app
        networks:
            - backend

networks:
    backend:
